deployments:
  - task: start
    reactor: p1
    node: node2@0.0.0.0
    connector1: f1
    connector2: f2
    sinks: s1
  - task: start
    reactor: p1
    node: node3@0.0.0.0
    connector1: t1
    connector2: t2
    sinks: s1
